---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Run Trivy vulnerability scanner"
        uses: "aquasecurity/trivy-action@master"
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"
      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: 'trivy-results.sarif'
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/actions/go-build@main"

  image-build:
    name: "Build Container Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/docker-build@main"
      - name: "Run Trivy vulnerability scanner"
        uses: "aquasecurity/trivy-action@master"
        with:
          image-ref: 'ghcr.io/vroldanbet/zed:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  unit:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/action-spicedb@v1"
      - uses: "authzed/actions/go-test@main"
